from pylab import *
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

rc('text', usetex=True)
rc('font', family='serif')

clf()
phi = np.loadtxt('phi_vals.dat', 'float')
r = np.loadtxt('r_vals.dat')
z = np.loadtxt('z_vals.dat')
Ez = np.loadtxt('Ez_vals.dat')
Er = np.loadtxt('Er_vals.dat')
contourf(r, z, phi, 100, cmap='gist_rainbow')
colorbar()
xlabel("$r$ (mm)")
ylabel("$z$ (mm)")
savefig('part1contour.png', dpi=300)
show()

clf()
w = np.array([1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
              1.7, 1.8, 1.9, 1.95, 1.99])
iterations = np.array([383, 344, 309, 276, 245, 246, 234,
                       206, 166, 139, 240, 896])
xlim(1, 2)
ylim(100, 900)
xlabel("$\omega$")
ylabel("$N$")
plot(w, iterations)
savefig('w_iter.png', dpi=300)
show()

clf()
plot(z, phi[:, 0])
xlim(-25, 25)
xlabel("$z$ (mm)")
ylabel("$V$ (Volts)")
savefig('Vz_plot.png', dpi=300)
show()

clf()
plot(z, Ez[:, 201])
xlim(-25, 25)
xlabel("$z$ (mm)")
ylabel("$E_z$ (V/mm)")
savefig('Ez_r0_plot.png', dpi=300)
show()

clf()
plot(z, phi[:, 51])
xlim(-10, 10)
xlabel("$z$ (mm)")
ylabel("$V$ (Volts)")
savefig('V_r2p5_plot.png', dpi=300)
show()

clf()
plot(z, Ez[:, 51])
xlim(-10, 10)
xlabel("$z$ (mm)")
ylabel("$E_z$ (V/mm)")
savefig('Ez_r2p5_plot.png', dpi=300)
show()

clf()
plot(z, Er[:, 51])
xlim(-10, 10)
xlabel("$z$ (mm)")
ylabel("$E_r$ (V/mm)")
savefig('Er_r2p5_plot.png', dpi=300)
show()

clf()
zM, rM = np.meshgrid(r, z)
ax = gca(projection='3d')
ax.plot_surface(zM, rM, phi, cmap='gist_rainbow')
ax.set_xlabel("$r$ (mm)")
ax.set_ylabel("$z$ (mm)")
ax.set_zlabel("$V$ (Volts)")
savefig('surface_plot.png', dpi=300)
show()
